name 'telegraf'
maintainer 'Byron Schaller'
maintainer_email 'byron.schaller@gmail.com'
license 'all_rights'
description 'Installs/Configures telegraf'
long_description 'Installs/Configures telegraf'
version '0.1.0'
supports 'ubuntu'
issues_url 'https://github.com/byronschaller/telegraf/issues'
source_url 'https://github.com/byronschaller/telegraf'
